testname: Evaluation perceptive
testId: facial-evaluation
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: false
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Page d'instruction
      content: content in GenericPage.js
    - type: test_page
      id: test_page
      name: Page de test
      content: Regardez une partie de la vidéo ci dessus.
      question: Entendez vous bien la vidéo ?
      add : Profitez de cette page pour faire vos réglages (son, zoom de la page...) 
      ref: Son de la vidéo
      stimuli: 
          C1: [test_video, configs/videos/video_test.mp4] 
    - 
          - random
          - type: video_believable
            id: scene2_sexisme_mic2_believability
            name: Page 1 of 22
            content: Regardez et évaluez les 4 vidéos ci dessus. (Sur cette page, il n'y a pas de son.)
            question: Selon vous, est ce que le comportement de l'agent ressemble à des comportements humains ?
            add: Comportement &#x2192; regard, expressions faciales et mouvements de tête
            ref: <strong>Ressemblance avec des comportements humains</strong>
            stimuli: 
                C1: [b_real_scene2_sexisme_mic2, configs/videos/scene2_sexisme_mic2/real.mp4]
                C2: [b_m1_scene2_sexisme_mic2, configs/videos/scene2_sexisme_mic2/50_700.mp4]
                C3: [b_m3_scene2_sexisme_mic2, configs/videos/scene2_sexisme_mic2/3_800.mp4]
                C4: [b_m2_scene2_sexisme_mic2, configs/videos/scene2_sexisme_mic2/6_700.mp4]       
          - type: video_synchronized
            id: scene2_sexisme_mic2_synchronization
            name: Page 2 of 22
            content: Regardez et évaluez les 4 vidéos ci dessus. (N'oubliez pas d'activer le son.)
            question: Selon vous, est ce que le comportement de l'agent est coordonné avec la parole (en termes de rythme et d'intonation) ?
            add: Comportement &#x2192; regard, expressions faciales et mouvements de tête
            ref: <strong>Coordination avec la parole</strong>
            stimuli: 
                C1: [s_real_scene2_sexisme_mic2, configs/videos/scene2_sexisme_mic2/real.mp4]
                C2: [s_m1_scene2_sexisme_mic2, configs/videos/scene2_sexisme_mic2/50_700.mp4]
                C3: [s_m3_scene2_sexisme_mic2, configs/videos/scene2_sexisme_mic2/3_800.mp4]
                C4: [s_m2_scene2_sexisme_mic2, configs/videos/scene2_sexisme_mic2/6_700.mp4]

          - type: video_believable
            id: scene5_confrontation1_mic1_believability
            name: Page 3 of 22
            content: Regardez et évaluez les 4 vidéos ci dessus. (Sur cette page, il n'y a pas de son.)
            question: Selon vous, est ce que le comportement de l'agent ressemble à des comportements humains ?
            add: Comportement &#x2192; regard, expressions faciales et mouvements de tête
            ref: <strong>Ressemblance avec des comportements humains</strong>
            stimuli: 
                C1: [b_real_scene5_confrontation1_mic1, configs/videos/scene5_confrontation1_mic1/real.mp4]
                C2: [b_m1_scene5_confrontation1_mic1, configs/videos/scene5_confrontation1_mic1/50_700.mp4] 
                C3: [b_m3_scene5_confrontation1_mic1, configs/videos/scene5_confrontation1_mic1/3_800.mp4]
                C4: [b_m2_scene5_confrontation1_mic1, configs/videos/scene5_confrontation1_mic1/6_700.mp4]
          - type: video_synchronized
            id: scene5_confrontation1_mic1_synchronization
            name: Page 4 of 22
            content: Regardez et évaluez les 4 vidéos ci dessus. (N'oubliez pas d'activer le son.)
            question: Selon vous, est ce que le comportement de l'agent est coordonné avec la parole (en termes de rythme et d'intonation) ?
            add: Comportement &#x2192; regard, expressions faciales et mouvements de tête
            ref: <strong>Coordination avec la parole</strong>
            stimuli: 
                C1: [s_real_scene5_confrontation1_mic1, configs/videos/scene5_confrontation1_mic1/real.mp4]
                C2: [s_m1_scene5_confrontation1_mic1, configs/videos/scene5_confrontation1_mic1/50_700.mp4]
                C3: [s_m3_scene5_confrontation1_mic1, configs/videos/scene5_confrontation1_mic1/3_800.mp4]  
                C4: [s_m2_scene5_confrontation1_mic1, configs/videos/scene5_confrontation1_mic1/6_700.mp4]

          - type: video_believable
            id: scene2_confrontation_prise1_mic1_believability
            name: Page 5 of 22
            content: Regardez et évaluez les 4 vidéos ci dessus. (Sur cette page, il n'y a pas de son.)
            question: Selon vous, est ce que le comportement de l'agent ressemble à des comportements humains ?
            add: Comportement &#x2192; regard, expressions faciales et mouvements de tête
            ref: <strong>Ressemblance avec des comportements humains</strong>
            stimuli: 
                C1: [b_real_scene2_confrontation_prise1_mic1, configs/videos/scene2_confrontation_prise1_mic1/real.mp4]
                C2: [b_m1_scene2_confrontation_prise1_mic1, configs/videos/scene2_confrontation_prise1_mic1/50_700.mp4]
                C3: [b_m3_scene2_confrontation_prise1_mic1, configs/videos/scene2_confrontation_prise1_mic1/3_800.mp4]    
                C4: [b_m2_scene2_confrontation_prise1_mic1, configs/videos/scene2_confrontation_prise1_mic1/6_700.mp4]  
          - type: video_synchronized
            id: scene2_confrontation_prise1_mic1_synchronization
            name: Page 6 of 22
            content: Regardez et évaluez les 4 vidéos ci dessus. (N'oubliez pas d'activer le son.)
            question: Selon vous, est ce que le comportement de l'agent est coordonné avec la parole (en termes de rythme et d'intonation) ?
            add: Comportement &#x2192; regard, expressions faciales et mouvements de tête
            ref: <strong>Coordination avec la parole</strong>
            stimuli: 
                C1: [s_real_scene2_confrontation_prise1_mic1, configs/videos/scene2_confrontation_prise1_mic1/real.mp4]
                C2: [s_m1_scene2_confrontation_prise1_mic1, configs/videos/scene2_confrontation_prise1_mic1/50_700.mp4]
                C3: [s_m3_scene2_confrontation_prise1_mic1, configs/videos/scene2_confrontation_prise1_mic1/3_800.mp4]
                C4: [s_m2_scene2_confrontation_prise1_mic1, configs/videos/scene2_confrontation_prise1_mic1/6_700.mp4]

          - type: video_believable
            id: scene3_sexisme_prise3_mic1_believability
            name: Page 7 of 22
            content: Regardez et évaluez les 4 vidéos ci dessus. (Sur cette page, il n'y a pas de son.)
            question: Selon vous, est ce que le comportement de l'agent ressemble à des comportements humains ?
            add: Comportement &#x2192; regard, expressions faciales et mouvements de tête
            ref: <strong>Ressemblance avec des comportements humains</strong>
            stimuli: 
                C1: [b_real_scene3_sexisme_prise3_mic1, configs/videos/scene3_sexisme_prise3_mic1/real.mp4]
                C2: [b_m1_scene3_sexisme_prise3_mic1, configs/videos/scene3_sexisme_prise3_mic1/50_700.mp4]
                C3: [b_m3_scene3_sexisme_prise3_mic1, configs/videos/scene3_sexisme_prise3_mic1/3_800.mp4]  
                C4: [b_m2_scene3_sexisme_prise3_mic1, configs/videos/scene3_sexisme_prise3_mic1/6_700.mp4]    
          - type: video_synchronized
            id: scene3_sexisme_prise3_mic1_synchronization
            name: Page 8 of 22
            content: Regardez et évaluez les 4 vidéos ci dessus. (N'oubliez pas d'activer le son.)
            question: Selon vous, est ce que le comportement de l'agent est coordonné avec la parole (en termes de rythme et d'intonation) ?
            add: Comportement &#x2192; regard, expressions faciales et mouvements de tête
            ref: <strong>Coordination avec la parole</strong>
            stimuli: 
                C1: [s_real_scene3_sexisme_prise3_mic1, configs/videos/scene3_sexisme_prise3_mic1/real.mp4]
                C2: [s_m1_scene3_sexisme_prise3_mic1, configs/videos/scene3_sexisme_prise3_mic1/50_700.mp4]
                C3: [s_m3_scene3_sexisme_prise3_mic1, configs/videos/scene3_sexisme_prise3_mic1/3_800.mp4]
                C4: [s_m2_scene3_sexisme_prise3_mic1, configs/videos/scene3_sexisme_prise3_mic1/6_700.mp4]
  
    - type: finish
      name: Merci !
      content: <strong>Merci pour votre participation (complétez bien cette page pour nous envoyer vos résultats)</strong><br><br>
      showResults: true
      writeResults: true
      questionnaire:
          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 30
          - type: likert
            name: gender
            label: Genre
            response:
             - value: female
               label: Femme
             - value: male
               label: Homme
             - value: other
               label: Autre
          - type: likert
            name: french_level
            label: Quel est votre niveau de français ?
            response:
             - value: experienced
               label: Expérimenté 
             - value: intermediate
               label: Intermédiaire
             - value: elementary
               label: Élémentaire
             - value: no_notion
               label: Aucune notion
          - type: likert
            name: video_game
            label: A quelle fréquence jouez-vous à des jeux vidéos dans lesquels <br> vous êtes amené à croiser/interagir avec des personnages non joueurs ?
            response:
             - value: often
               label: Souvent
             - value: sometimes
               label: Parfois
             - value: rarely
               label: Rarement
             - value: never
               label: Jamais
          - type: likert
            name: animation_movies
            label: A quelle fréquence voyez-vous des films d'animation ?
            response:
             - value: often
               label: Souvent
             - value: sometimes
               label: Parfois
             - value: rarely
               label: Rarement
             - value: never
               label: Jamais
