testname: Facial behaviours evaluation
testId: facial-evaluation
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: false
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Welcome
      content: Welcome to facial behaviours evaluation!       
    - 
          - random
          - type: video_believable
            id: scene2_sexisme_mic2_believability
            name: Page 1 of 22
            content: Rate the videos shown below (for this condition there is NO sound)
            question: How human-like was the agent in this video?
            stimuli: 
                C1: [b_real_scene2_sexisme_mic2, configs/videos/scene2_sexisme_mic2/real.mp4]
                C2: [b_m1_scene2_sexisme_mic2, configs/videos/scene2_sexisme_mic2/50_700.mp4]
                C3: [b_m3_scene2_sexisme_mic2, configs/videos/scene2_sexisme_mic2/3_800.mp4]
                C4: [b_m2_scene2_sexisme_mic2, configs/videos/scene2_sexisme_mic2/6_700.mp4]       
          - type: video_synchronized
            id: scene2_sexisme_mic2_synchronization
            name: Page 2 of 22
            content: Rate the videos shown below (for this condition there is sound)
            question: How well the agent's behavior matches the speech (in terms of rhythm, intonation of speech) ?
            stimuli: 
                C1: [s_real_scene2_sexisme_mic2, configs/videos/scene2_sexisme_mic2/real.mp4]
                C2: [s_m1_scene2_sexisme_mic2, configs/videos/scene2_sexisme_mic2/50_700.mp4]
                C3: [s_m3_scene2_sexisme_mic2, configs/videos/scene2_sexisme_mic2/3_800.mp4]
                C4: [s_m2_scene2_sexisme_mic2, configs/videos/scene2_sexisme_mic2/6_700.mp4]

          - type: video_believable
            id: scene5_confrontation1_mic1_believability
            name: Page 3 of 22
            content: Rate the videos shown below (for this condition there is NO sound)
            question: How human-like was the agent in this video?
            stimuli: 
                C1: [b_real_scene5_confrontation1_mic1, configs/videos/scene5_confrontation1_mic1/real.mp4]
                C2: [b_m1_scene5_confrontation1_mic1, configs/videos/scene5_confrontation1_mic1/50_700.mp4] 
                C3: [b_m3_scene5_confrontation1_mic1, configs/videos/scene5_confrontation1_mic1/3_800.mp4]
                C4: [b_m2_scene5_confrontation1_mic1, configs/videos/scene5_confrontation1_mic1/6_700.mp4]
          - type: video_synchronized
            id: scene5_confrontation1_mic1_synchronization
            name: Page 4 of 22
            content: Rate the videos shown below (for this condition there is sound)
            question: How well the agent's behavior matches the speech (in terms of rhythm, intonation of speech) ?
            stimuli: 
                C1: [s_real_scene5_confrontation1_mic1, configs/videos/scene5_confrontation1_mic1/real.mp4]
                C2: [s_m1_scene5_confrontation1_mic1, configs/videos/scene5_confrontation1_mic1/50_700.mp4]
                C3: [s_m3_scene5_confrontation1_mic1, configs/videos/scene5_confrontation1_mic1/3_800.mp4]  
                C4: [s_m2_scene5_confrontation1_mic1, configs/videos/scene5_confrontation1_mic1/6_700.mp4]

          - type: video_believable
            id: scene2_confrontation_prise1_mic1_believability
            name: Page 5 of 22
            content: Rate the videos shown below (for this condition there is NO sound)
            question: How human-like was the agent in this video?
            stimuli: 
                C1: [b_real_scene2_confrontation_prise1_mic1, configs/videos/scene2_confrontation_prise1_mic1/real.mp4]
                C2: [b_m1_scene2_confrontation_prise1_mic1, configs/videos/scene2_confrontation_prise1_mic1/50_700.mp4]
                C3: [b_m3_scene2_confrontation_prise1_mic1, configs/videos/scene2_confrontation_prise1_mic1/3_800.mp4]    
                C4: [b_m2_scene2_confrontation_prise1_mic1, configs/videos/scene2_confrontation_prise1_mic1/6_700.mp4]  
          - type: video_synchronized
            id: scene2_confrontation_prise1_mic1_synchronization
            name: Page 6 of 22
            content: Rate the videos shown below (for this condition there is sound)
            question: How well the agent's behavior matches the speech (in terms of rhythm, intonation of speech) ?
            stimuli: 
                C1: [s_real_scene2_confrontation_prise1_mic1, configs/videos/scene2_confrontation_prise1_mic1/real.mp4]
                C2: [s_m1_scene2_confrontation_prise1_mic1, configs/videos/scene2_confrontation_prise1_mic1/50_700.mp4]
                C3: [s_m3_scene2_confrontation_prise1_mic1, configs/videos/scene2_confrontation_prise1_mic1/3_800.mp4]
                C4: [s_m2_scene2_confrontation_prise1_mic1, configs/videos/scene2_confrontation_prise1_mic1/6_700.mp4]

          - type: video_believable
            id: scene3_sexisme_prise3_mic1_believability
            name: Page 7 of 22
            content: Rate the videos shown below (for this condition there is NO sound)
            question: How human-like was the agent in this video?
            stimuli: 
                C1: [b_real_scene3_sexisme_prise3_mic1, configs/videos/scene3_sexisme_prise3_mic1/real.mp4]
                C2: [b_m1_scene3_sexisme_prise3_mic1, configs/videos/scene3_sexisme_prise3_mic1/50_700.mp4]
                C3: [b_m3_scene3_sexisme_prise3_mic1, configs/videos/scene3_sexisme_prise3_mic1/3_800.mp4]  
                C4: [b_m2_scene3_sexisme_prise3_mic1, configs/videos/scene3_sexisme_prise3_mic1/6_700.mp4]    
          - type: video_synchronized
            id: scene3_sexisme_prise3_mic1_synchronization
            name: Page 8 of 22
            content: Rate the videos shown below (for this condition there is sound)
            question: How well the agent's behavior matches the speech (in terms of rhythm, intonation of speech) ?
            stimuli: 
                C1: [s_real_scene3_sexisme_prise3_mic1, configs/videos/scene3_sexisme_prise3_mic1/real.mp4]
                C2: [s_m1_scene3_sexisme_prise3_mic1, configs/videos/scene3_sexisme_prise3_mic1/50_700.mp4]
                C3: [s_m3_scene3_sexisme_prise3_mic1, configs/videos/scene3_sexisme_prise3_mic1/3_800.mp4]
                C4: [s_m2_scene3_sexisme_prise3_mic1, configs/videos/scene3_sexisme_prise3_mic1/6_700.mp4]
  
    - type: finish
      name: Thank you
      content: Thank you for attending!
      showResults: true
      writeResults: true
      questionnaire:
          - type: text
            label: eMail
            name: email
          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 30
          - type: likert
            name: gender
            label: Gender
            response:
             - value: female
               label: Female
             - value: male
               label: Male
             - value: other
               label: Other